# Generated by Django 6.0.1 on 2026-01-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_author_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
