# Generated by Django 5.2.4 on 2026-01-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_author_biography_alter_author_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma separated tags', max_length=200),
        ),
    ]
